### PR TITLE
Fix dashboard logo height in mobile view #285

### LINKED ISSUE #285: Mobile issue (logo)
STR:

1. Navigate to localhost:5080
2. Resize the screen until the navigation bar collapses
3. Click the hamburger icon (the three horizontal lines)
4. Hover on the text "Taskcluster"

Expected: The "T" logo should be relatively same size as the hamburger menu
Actual: The "T" logo is much bigger than the hamburger menu

screen shot 2018-11-14 at 11 51 12 am

### PR DESCRIPTION
**Pull request by OjaswinM**
Adjusted the height of logo in mobile view

image

Fixes #285

### CODE REVIEW

File: src/components/Dashboard/index.jsx [hunk 1]
```diff
@@ -217,7 +217,7 @@ export default class Dashboard extends Component {
             {showLogo ? (
               <img
                 className={classes.logoStyle}
-                height={40}
+                height={mobileOpen ? 30 : 40}
```
Comment (helfi92) [inline src/components/Dashboard/index.jsx]: Let's have the logo be the same height for both desktop and mobile.

```jsx
height={30}
```

Comment (OjaswinM) [reply src/components/Dashboard/index.jsx]: Gotcha! :)
