### PR TITLE
Fix favicon logo not loading #270

### LINKED ISSUE #270: Visual indication of a task group state
A user will want to do other things while waiting for a task group to finish. This can be solved by modifying the favicon to have a yellow, green or red circle beside the Logo to indicate the status of a task group. When the user leaves the task group view, we should bring back the original favicon.

### PR DESCRIPTION
**Pull request by projectyang**
Images will now be properly loaded by webpack for favicon link.

Fixes #270

### CODE REVIEW

File: src/components/Helmet/index.jsx [hunk 1]
```diff
@@ -20,19 +24,25 @@ export default class Helmet extends Component {
...
       <ReactHelmet>
-        {state ? (
-          <link
-            href={`/src/images/logo${lowerCase(state)}.png`}
-            rel="shortcut icon"
-          />
-        ) : (
-          <link href="/src/images/logo.png" rel="shortcut icon" />
-        )}
+        <link href={this.getFavicon()} rel="shortcut icon" />
```
Comment (helfi92) [inline src/components/Helmet/index.jsx]: Change to:

```jsx
const Favicon = this.getFavicon();

...

<link href={Favicon} rel="shortcut icon" />
```
